version: "2"
services:
  web:
    # use current dir as context

      # build from Dockerfile.dev

      # run node server.js as command

    # mount current dir to app volume

    # add /app/node_modules not mounted to host\

    # map port 80 to port 3000
