version: 2
jobs:
  build:
    docker:
      - image: dataduke/sample-node
    steps:
      - checkout
  test:
    docker:
      - image: dataduke/sample-node
    steps:
      - checkout
      - run: npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
